
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - name: spotify repo
      apt_repository: repo="deb http://repository.spotify.com stable non-free"
      tags: [packages, internet, multimedia, spotify]
    - name: spotify key
      apt_key: keyserver=keyserver.ubuntu.com id=94558F59
      tags: [packages, internet, multimedia, spotify]
    - name: dropbox repo
      apt_repository: repo="deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main"
      tags: [packages, internet, dropbox]
    - name: dropbox repo
      apt_key: keyserver=pgp.mit.edu id=5044912E
      tags: [packages, internet, dropbox]
    - name: virtualbox repo
      apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
      tags: [packages, virtualization, virtualbox]
    - name: virtualbox key
      apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc 
      tags: [packages, virtualization, virtualbox]
    - name: steam repo
      apt_repository: repo="deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam"
      tags: [packages, games, steam]
    - name: steam key
      apt_key: url=http://repo.steampowered.com/steam/signature.gpg
      tags: [packages, games, steam]
    - name: install packages
      apt: name={{ item }}
      with_items: packages
