
- hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/spotify.yml tags=spotify,desktop
    - include: tasks/dropbox.yml tags=dropbox,desktop
    - include: tasks/virtualbox.yml tags=virtualbox,desktop 
    - include: tasks/steam.yml tags=steam,desktop
    - include: tasks/dotfiles.yml tags=dotfiles,programing,server
    - include: tasks/vim.yml tags=vim,programing
