- name: dropbox repo
  apt_repository: repo="deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main"
  sudo: yes
- name: dropbox key
  apt_key: keyserver=pgp.mit.edu id=5044912E
  sudo: yes
- name: dropbox package
  apt: name=dropbox update_cache=yes
  sudo: yes
