- name: configure dropbox repo
  apt_repository: repo="deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main"
  become: yes

- name: install dropbox key
  apt_key: keyserver=pgp.mit.edu id=5044912E
  become: yes

- name: install dropbox package
  apt: name=dropbox update_cache=yes
  become: yes
