
- block:
    - name: configure dropbox repo
      apt_repository:
        repo: "deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ custom_distribution_release }} main"
        filename: dropbox

    - name: install dropbox repo key
      apt_key: keyserver=pgp.mit.edu id=5044912E

    - name: install dropbox package
      apt: name=dropbox update_cache=yes

  when: ansible_os_family == 'Debian'
  become: yes
