
- name: install git
  apt:
    name:
      - git
      - git-extras
    update_cache: yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: link git config
  command: "{{ stow_program }} git"
  args:
    chdir: "{{ dotfiles_path }}"
