- name: install pip related packages
  apt: name={{ item }}
  become: yes
  with_items:
    - python-dev
    - python-pip

- name: update pip 
  pip: name=pip state=latest executable=/usr/bin/pip
  become: yes
