
- block:
    - name: install pip3 related packages
      apt: name={{ item }}
      with_items:
        - python3-dev
        - python3-pip

    - name: update pip3
      pip: name=pip state=latest executable=/usr/bin/pip3
  become: yes
  when: ansible_os_family == 'Debian'
