- name: install python packages from system repositories
  apt: name={{ item }}
  sudo: yes
  with_items:
    - python3-dev
    - python3-pip
- name: install python packages from pypi repositories
  pip: name={{ item }} executable=
  sudo: yes
  with_items:
    - virtualenv
    - virtualenvwrapper
