- block:
    - name: config distro repo
      apt_repository: repo="deb http://es.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main universe restricted multiverse"

    - name: config security repo
      apt_repository: repo="deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security main universe restricted multiverse"

    - name: config updates repo
      apt_repository: repo="deb http://es.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main universe restricted multiverse"

    - name: config backports repo
      apt_repository: repo="deb http://es.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main universe restricted multiverse"

    - name: delete main sources.list
      file: path=/etc/apt/sources.list state=absent

    - name: create empty sources.list
      file: path=/etc/apt/sources.list state=touch

  when: ansible_distribution == "Ubuntu"
  become: yes
