- name: steam repo
  apt_repository: repo="deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam"
  sudo: yes
- name: steam key
  apt_key: url=http://repo.steampowered.com/steam/signature.gpg
  sudo: yes
- name: steam package
  apt: name=steam-launcher update_cache=yes
  sudo: yes
