
- block:
    - name: config steam repo
      apt_repository:
        repo: "deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam"
        filename: steam

    - name: install steam repo key
      apt_key: url=http://repo.steampowered.com/steam/archive/precise/steam.gpg

    - name: install steam package
      apt: name=steam update_cache=yes
      ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  when: ansible_os_family == 'Debian'
