- name: config steam repo
  lineinfile: 
    dest: /etc/apt/sources.list.d/steam.list
    create: yes
    mode: 0644
    owner: root
    group: root
    line: "deb [arch=amd64,i386] http://repo.steampowered.com/steam/ precise steam"
  become: yes

- name: install steam key
  apt_key: url=http://repo.steampowered.com/steam/signature.gpg
  become: yes

- name: install steam package
  apt: name=steam-launcher update_cache=yes
  become: yes
