
- block:
    - name: install sudo package
      apt: name=sudo

    - name: current user can sudo without password
      lineinfile:
        dest: /etc/sudoers.d/{{ ansible_user_id }}
        create: yes
        mode: 0440
        owner: root
        group: root
        regexp: "^{{ ansible_user_id }}"
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
        validate: "/usr/sbin/visudo -cf %s"
  become: yes
  when: ansible_os_family == 'Debian'
