- name: install sudo package
  apt: name=sudo

- name: current user can sudo without password
  become: yes
  lineinfile: 
    dest: /etc/sudoers.d/{{ ansible_ssh_user }}
    create: yes
    mode: 0440
    owner: root
    group: root
    regexp: "^{{ ansible_ssh_user }}" 
    line: "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
