
- name: install tmux
  apt: name=tmux update_cache=yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: link tmux config
  command: "{{ stow_program }} tmux"
  args:
    chdir: "{{ dotfiles_path }}"
