- name: config virtualbox repo
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
  become: yes

- name: install virtualbox key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc 
  become: yes

- name: install virtualbox package
  apt: name=virtualbox update_cache=yes
  become: yes

- name: add actual user to vboxusers
  user: name={{ ansible_user_id }} groups=vboxusers
  become: yes
