- name: config virtualbox repo
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
  sudo: yes

- name: install virtualbox key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc 
  sudo: yes

- name: install virtualbox package
  apt: name=virtualbox update_cache=yes
  sudo: yes
