- name: config weechat repo
  apt_repository: repo="deb https://weechat.org/ubuntu {{ ansible_distribution_release }} main"
  become: yes

- name: install weechat repo key
  apt_key: keyserver=pool.sks-keyservers.net id=11E9DE8848F2B65222AA75B8D1820DB22A11534E
  become: yes

- name: install weechat package
  apt: name={{ item }} update_cache=yes
  become: yes
  with_items:
    - weechat-curses
    - weechat-plugins
