
- name: install zsh
  apt: name=zsh update_cache=yes
  become: yes
  when: ansible_os_family == 'Debian'

- name: link zsh config
  command: "{{ stow_program }} zsh"
  args:
    chdir: "{{ dotfiles_path }}"

- name: change actual user shell
  user: name={{ ansible_user_id }} shell=/bin/zsh
  become: yes
