- name: install zsh
  apt: name=zsh update_cache=yes
  sudo: yes

- name: link zsh config
  command: "/usr/bin/{{ stow_program }} zsh"
  args:
    chdir: "{{ dotfiles_path }}"

- name: change actual user shell
  user: name={{ ansible_ssh_user }} shell=/bin/zsh
  sudo: yes
